version: '3'

services:
  regression:
    image: regression-flask:latest
    container_name: regression-flask
    build: .
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./server:/app/server
    env_file:
      - .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - 5002:5000
    networks:
      - machine-learning

  minio:
    restart: always
    image: minio/minio:latest
    container_name: mlflow_flask_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ml_flask_minio_data:/data
    networks:
      - machine-learning

  mc:
    image: minio/minio:latest
    depends_on:
      - minio
    container_name: flask_mc
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /tmp/wait-for-it.sh minio:9000 &&
      /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
      /usr/bin/mc mb minio/mlflow;
      exit 0;
      "
    volumes:
      - ./tmp/wait-for-it.sh:/tmp/wait-for-it.sh
    networks:
      - machine-learning

  db:
    restart: always
    image: mysql:8
    container_name: mlflow_flask_db
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ml_flask_dbdata:/var/lib/mysql
    networks:
      - machine-learning

  web:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_flask_server
    depends_on:
      - mc
      - db
    ports:
      - "5001:5000"
    volumes:
      - ./scripts:/opt/mlflow/scripts
    env_file:
      - .env
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0
    networks:
      - machine-learning

volumes:
    ml_flask_minio_data:
    ml_flask_dbdata:

networks:
  machine-learning:
    name: machine-learning
